# Generated by Django 6.1.1 on 2026-09-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userhandle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhandle',
            name='platform',
            field=models.CharField(choices=[('CF', 'Codeforces'), ('CC', 'CodeChef'), ('AC', 'AtCoder'), ('LC', 'LeetCode')], max_length=2),
        ),
    ]
