# Generated by Django 6.1.1 on 2026-09-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=255)),
                ('problem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField()),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_submissions', to='tracker.userhandle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
